databases:
  - name: truestate-db
    plan: free
    databaseName: truestate
    postgresMajorVersion: 16

services:
  # Backend (Django)
  - type: web
    name: truestate-backend
    env: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: truestate-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: truestate-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://truestate-frontend.onrender.com

  # Frontend (Vite React)
  - type: web
    name: truestate-frontend
    env: static
    rootDir: frontend/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://truestate-backend.onrender.com/api
